MA-1401: Generate alerts / tickets when account regisration fails with ESB / IT
SungardAS/aws-services-onboarding pull request #7
Opened 2017-08-09 05:23 UTC by chandramishra

**Purpose:** Send alert mail when account registration with billing system has been failed
For more details Please refer this link : https://mountdiablo.jira.com/browse/MA-1401?filter=-1
**Changes:**  API and aws-services-onboarding micro services
**Integration testing/functional testing:**
1) Create account when billing system not reachable
2) Create account with wrong api & secret key
3) Create account with existing email id
‌
**Unit Testing**
Not Available

2017-08-09 05:41 UTC, RajkumarShivage approved these changes
LGTM

2017-08-14 07:51 UTC, RajkumarShivage requested changes

2017-08-14 07:51 UTC, RajkumarShivage commented on src/index_enable_billing_activation.js
> +  console.log(billingUrl);
We should not print or log the access and secret key. Please remove access and secret key from console log.

2017-08-14 07:51 UTC, RajkumarShivage commented on src/index_enable_billing_activation.js
>    console.log(bodyjson);
It is not recommended to print or log the access and secret key.

2017-08-14 07:51 UTC, RajkumarShivage commented on src/index_enable_billing_activation.js
> +      sendAlertMailBySes(billingInfo, errmsg, billingInfo);
Is there a requirement to send an email if account creation fails?

2017-08-14 07:51 UTC, RajkumarShivage commented on src/index_enable_billing_activation.js
> +    sendAlertMailBySes(billingInfo, 'Found Error While Creating Account');
Is there a requirement to send an email if account creation fails?

2017-08-14 08:12 UTC, chandramishra commented on src/index_enable_billing_activation.js
> +      sendAlertMailBySes(billingInfo, errmsg, billingInfo);
no any requirement . I did additional just for tracking but any way i can comment code for send alert mail

2017-08-14 08:38 UTC, RajkumarShivage approved these changes

2017-08-14 09:19 UTC, SonalOjha approved these changes
Looks fine

2017-08-14 09:44 UTC, merged